package edu.asu.zoophy.genbankfactory.database;

/**
 * Class to hold data for PubMed Articles
 * @author demetri/Davy
 */
public class Publication {
	//Autogenerated DB ID//
	private int pubId;
	//PubMed Article ID//
	private int pubmedId;
	//PubMed Central ID from the PubMed Site//
	private String centralId;
	private String authors;
	private String title;
	private String journal;
	
	public Publication() {
		//Default//
	}

	public int getPubId() {
		return pubId;
	}

	public void setPubId(int pubId) {
		this.pubId = pubId;
	}

	public int getPubmedId() {
		return pubmedId;
	}

	public void setPubmedId(int pubmedId) {
		this.pubmedId = pubmedId;
	}

	public String getCentralId() {
		return centralId;
	}

	public void setCentralId(String centralId) {
		this.centralId = centralId;
	}

	public String getAuthors() {
		return authors;
	}

	public void setAuthors(String authors) {
		this.authors = authors;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getJournal() {
		return journal;
	}

	public void setJournal(String journal) {
		this.journal = journal;
	}
}